# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RsQ-vI-QMjjQsueHdWsbYdHNyZIimDp
"""

#Calculadora com Estrutura Condicional
print("Calculadora")

num1 = int(input("Digite um número: "))
num2 = int(input("Digite outro número: "))

print("Escolha o tipo de operação: Multiplicação, Divisão, Subtração, Adição")

usuario_escolha = input("Qual operação você deseja fazer? ")

if usuario_escolha == "Multiplicação":
  multi = num1 * num2
  print("Resultado: ", multi)

elif usuario_escolha == "Divisão":
  divi = num1 / num2
  print("Resultado: ", divi)
  resto_divi = input("Ver o resto da Divisão? S/N: ")

  if resto_divi == "S":
    resto = num1 % num2
    print("O resto é: ", resto)

  else:
    print("Operação encerrada")

elif usuario_escolha == "Subtração":
  sub = num1 - num2
  print("Resultado: ", sub)

elif usuario_escolha == "Adição":
  adi = num1 + num2
  print("Resultado: ", adi)

else:
  print("Opção inválida.")

#Calculadora com estrutura de repetição While

opcao = ""

while opcao != "5":

  print("=== Calculadora ===")
  print("1 - Adição: ")
  print("2 - Subtração: ")
  print("3 - Multiplicação: ")
  print("4 - Divisão: ")
  print("5 - Sair.")

  opcao = input("Selecione uma operação: ")

  if opcao == "5":
    print("Calculadora encerrada.")
    break

  if opcao in ["1", "2", "3", "4"]:
    num1 = float(input("Digite um número: "))
    num2 = float(input("Digite outro número: "))

    if opcao == "1":
      resultado = num1 + num2
      print("O resultado é: ", resultado)

    elif opcao == "2":
      resultado = num1 - num2
      print("O resultado é: ", resultado)

    elif opcao == "3":
       resultado = num1 * num2
       print("O resultado é: ", resultado)

    elif opcao == "4":
       resultado = num1 / num2
       print("O resultado é: ", resultado)

  else:
    print("Por favor, tente novamente")

